### ISSUE TITLE
Services missing

### ISSUE THREAD

**Issue by Pfeil** [kit-data-manager/webpage#12]
- [x] WAP Server #18
- [x] FAIRDOscope #19
- [x] Data Collections Explorer #16 
- ~~Query Service (Does it have another name?)~~ -> not a new service, just adjustments for a project
- ~~Annotation Editor (AKITA/TUHL?)~~ -> application case
- ~~EVOKS~~ (postponed, requires further code review)
- ~~HMC Profile~~ (would rather like to add this as a part of something related, e.g., an application case page or Typed PID Maker)

Please extend. You may use the list (see their hedgedoc pad) of TF Services and Architecture for inspiration, I am not always sure what to add from it.

**Comment by pjoKIT** [comment]
- EVOKS
- Data Collections Explorer
- Query Service
- Annotation Editor
- FAIR DOscope

**Comment by Pfeil** [comment]
Thanks! I merged it into the list above because the ones in the first comment are collected by github and treated as some kind of todo list in the issue overview. Not sure if I know the Query Service, it is this thing which is also used by wikidata to do sparql queries or do we have something else here?

**Comment by pjoKIT** [comment]
> Not sure if I know the Query Service, it is this thing which is also used by wikidata to do sparql queries or do we have something else here?

Yes, that is an adaption of the Wikidata Query Service.

**Comment by pjoKIT** [comment]
This should be a near complete list of services still missing:
- EVOKS
- tAKITA/TUHLS
- PLATIN (GeoBrowser)
- QueryService
- Annotation Editor
- Ingest GUI
- SWATI

- Fairdoscope
- FAIR Digital Object Ecosystem Testbed

- Metadata Schemas for Materials Science
- MDMC-NEP top-level Ontology

- Service Base Module
- Repository Service Core
- Gateway
- Benchmarks for RO-Crate libraries
- Frontend-collection
- Overview of Existing (Metadata) Repository Platforms
- Monitoring4NEP
- Katacoda-scenarios
- Collection-API (is this the same as the Collection Registry?)
- Available UIs (Frontend-collection?)
- Available/Examples for Indexing Service
- KIT Data Manager - Generic Message Consumer
- bagit-provider-plugin
- KIT Data Manager - Monitoring-Service
- Gemma
- gemma-plugin
- Notification Service
- Web Annotation Protocol Server
- KIT Data Manager - template
- admin-ui 
- docker-kitdm-2.0

**Comment by ThomasJejkal** [comment]
I think it's not feasible to create entries for all repositories in our GitHub organization but only for "high-level" services and tools which can be operated more or less standalone. Furthermore, I see differences in the role of the listed software packages. Some are really base services, others might fit better in the (not yet existing) group of application cases. 

Below, I tried to annotate the list entries after the following scheme:

✅  Service missing
💡 Application case
🧰 Tool/Library/Schema used/documented in other services
💀 Discontinued
❔ Unsure/too specific

> * EVOKS ✅
> * tAKITA/TUHLS 💡 
> * PLATIN (GeoBrowser) ❔  
> * QueryService ❔ 
> * Annotation Editor 💡 
> * Ingest GUI 💡 
> * SWATI 🧰 
> * Fairdoscope 💡 
> * FAIR Digital Object Ecosystem Testbed 💡 
> * Metadata Schemas for Materials Science 🧰 
> * MDMC-NEP top-level Ontology  🧰  
> * Service Base Module 🧰 
> * Repository Service Core 🧰 
> * Gateway ❔ (too early to present)
> * Benchmarks for RO-Crate libraries 🧰 
> * Frontend-collection 💡 
> * Overview of Existing (Metadata) Repository Platforms ❔ 
> * Monitoring4NEP 🧰 
> * Katacoda-scenarios ❔ 
> * Collection-API (is this the same as the Collection Registry? --> Yes) ✅ 
> * Available UIs (Frontend-collection?) 💡 
> * Available/Examples for Indexing Service ❔ 
> * KIT Data Manager - Generic Message Consumer 🧰 
> * bagit-provider-plugin 🧰 
> * KIT Data Manager - Monitoring-Service 💀 
> * Gemma 🧰 
> * gemma-plugin 🧰 
> * Notification Service 💀 
> * Web Annotation Protocol Server ✅ 
> * KIT Data Manager - template (is this really needed in a public overview?) 🧰 
> * admin-ui 💀 
> * docker-kitdm-2.0 💀

**Comment by Pfeil** [comment]
Has there been any finalization on this decision on Wednesday? I could update the list in the top comment then, accordingly. Top-comment-lists are seen as to-dos in the list of issues, which I find quiet useful.

**Comment by Pfeil** [comment]
~~Evoks will be done by me and Gulzaure~~

WAP Server by Thomas

I will update the list above.

**Comment by Pfeil** [comment]
All tasks that were agreed on are solved. I'll close it for now.
